"use client";
import { useParams } from "next/navigation";
import { useState } from "react";
import { invoices } from "@/lib/demo-data";
import { formatINR, formatDate } from "@/lib/format";
import { PageHeader, Status } from "@/components/ui";

export default function InvoiceDetailPage() {
  const params = useParams<{ number: string }>(); const invoice = invoices.find((item) => item.number === params.number) ?? invoices[0]; const [status, setStatus] = useState(invoice.status); const [message, setMessage] = useState("");
  async function paymentRequest() { const response = await fetch("/api/payment-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ invoiceNumber: invoice.number, amount: invoice.total }) }); const body = await response.json(); setMessage(response.ok ? `Payment link ready: ${body.url}` : body.error); }
  return <><PageHeader eyebrow="Invoice detail" title={invoice.number} action={<div className="form-actions no-print"><button className="secondary" onClick={() => window.print()}>Print</button>{status !== "PAID" && <button onClick={paymentRequest}>Create payment request</button>}</div>} />{message && <p className="notice">{message}</p>}<article className="invoice-paper"><div className="invoice-top"><div><p className="eyebrow">CoolCare Services</p><h2>Tax Invoice</h2><p className="muted">GSTIN: 29AAAAA0000A1Z5</p></div><div className="invoice-meta"><strong>{invoice.number}</strong><br />Issued 26 Jul 2026<br />Due {formatDate(invoice.due)}<br /><br /><Status value={status} /></div></div><div className="split" style={{ margin: "18px 0" }}><div><p className="eyebrow">Bill to</p><strong>{invoice.customer}</strong><br /><span className="muted">Bengaluru, Karnataka</span></div><div><p className="eyebrow">Payment terms</p><strong>Due on receipt</strong><br /><span className="muted">UPI / card / bank transfer</span></div></div><div className="data-list"><div className="row"><div><strong>{invoice.service}</strong><span>1 × service · GST 18%</span></div><strong>{formatINR(Math.round(invoice.total / 1.18))}</strong></div><div className="row"><span>GST</span><strong>{formatINR(invoice.total - Math.round(invoice.total / 1.18))}</strong></div></div><div className="invoice-total"><span>Total payable</span><span>{formatINR(invoice.total)}</span></div>{status !== "PAID" && <div className="form-actions no-print"><button onClick={() => { setStatus("PAID"); setMessage("Payment recorded in this demo."); }}>Record payment</button></div>}</article></>;
}
