import Link from "next/link";
import { activities, invoices, quotes } from "@/lib/demo-data";
import { formatINR } from "@/lib/format";
import { PageHeader, Status } from "@/components/ui";

export default function Dashboard() {
  const due = invoices.filter((x) => x.status !== "PAID").reduce((sum, x) => sum + x.total, 0);
  return <><PageHeader eyebrow="Saturday, 26 July" title="Keep today moving" action={<Link href="/jobs" className="button">+ Capture a job note</Link>} /><section className="command"><div><p className="eyebrow">Cash desk</p><h2>{formatINR(due)} to collect</h2><p>Two invoices need your attention this week.</p></div><Link href="/follow-ups" className="text-link">Open follow-up queue →</Link></section><section className="split"><div className="panel"><div className="panel-title"><h2>Actionable totals</h2><span>Today</span></div><dl className="totals"><div><dt>Due today</dt><dd>{formatINR(2655)}</dd><small>1 payment reminder</small></div><div><dt>Overdue</dt><dd>{formatINR(2655)}</dd><small>1 invoice</small></div><div><dt>Draft quotes</dt><dd>1</dd><small>{formatINR(1770)} pending</small></div></dl></div><div className="panel"><div className="panel-title"><h2>Recent activity</h2><span className="live-dot">Live demo</span></div><ol className="timeline">{activities.map((a) => <li key={a.body}><time>{a.time}</time><span>{a.body}</span></li>)}</ol></div></section><section className="panel"><div className="panel-title"><h2>Open documents</h2><Link href="/invoices">View all</Link></div><div className="data-list">{[...invoices.slice(0, 2), ...quotes.slice(0, 1)].map((doc) => <div className="row" key={doc.id}><div><strong>{doc.number}</strong><span>{doc.customer} · {doc.service}</span></div><div className="row-end"><strong>{formatINR(doc.total)}</strong><Status value={doc.status} /></div></div>)}</div></section></>;
}
