"use client";
import { useState } from "react";
import { formatINR } from "@/lib/format";
import { PageHeader } from "@/components/ui";

type Parsed = { customerName?: string; dueDate?: string; paymentTerms: string; lines: { description: string; quantity: number; unitPrice: number; taxRate: number }[] };
export default function JobsPage() {
  const [note, setNote] = useState("Ravi Sharma, 2 AC services at 650 each, GST 18%, due 30 July 2026"); const [parsed, setParsed] = useState<Parsed | null>(null); const [error, setError] = useState("");
  async function parse() { setError(""); const response = await fetch("/api/jobs/parse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ note }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Could not parse this note."); return; } setParsed(body.data); }
  const subtotal = parsed?.lines.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0) ?? 0; const tax = parsed?.lines.reduce((sum, line) => sum + Math.round(line.quantity * line.unitPrice * line.taxRate / 100), 0) ?? 0;
  return <><PageHeader eyebrow="Capture while it is fresh" title="New job" /><section className="split"><div className="panel"><div className="panel-title"><h2>Voice-note transcript or typed note</h2><span>Local parser</span></div><div className="field"><label htmlFor="note">What needs doing?</label><textarea id="note" value={note} onChange={(e) => setNote(e.target.value)} /></div>{error && <p className="notice">{error}</p>}<div className="form-actions"><button onClick={parse}>Parse job note</button><span className="muted">No audio leaves your device in demo mode.</span></div></div><div className="panel"><div className="panel-title"><h2>Structured details</h2><span>Editable before sending</span></div>{parsed ? <div className="data-list"><div className="row"><div><span>Customer</span><strong>{parsed.customerName || "Choose customer"}</strong></div></div>{parsed.lines.map((line, index) => <div className="row" key={index}><div><strong>{line.description}</strong><span>{line.quantity} × {formatINR(line.unitPrice)} · GST {line.taxRate}%</span></div><strong>{formatINR(line.quantity * line.unitPrice)}</strong></div>)}<div className="row"><div><span>Due date</span><strong>{parsed.dueDate ?? "On receipt"}</strong></div></div><div className="invoice-total"><span>Quote total</span><span>{formatINR(subtotal + tax)}</span></div><div className="form-actions"><button>Create draft quote</button><button className="secondary">Save as job</button></div></div> : <p className="muted">Parse a note to review the customer, services, GST and due date here.</p>}</div></section></>;
}
